<Project Sdk="nanoFramework.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SmokeTest</RootNamespace>
    <AssemblyName>SmokeTest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nanoFramework.CoreLibrary" Version="1.17.11" />
  </ItemGroup>

</Project>
