<Project Sdk="nanoFramework.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SmokeTest</RootNamespace>
    <AssemblyName>SmokeTest</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <_NanoMdpGenerateStubs>true</_NanoMdpGenerateStubs>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nanoFramework.CoreLibrary" Version="2.0.0-preview.52" />
  </ItemGroup>

</Project>
